---
sudo: required
services: docker
addons:
  apt:
    packages:
      - docker-ce
language: ruby
#https://www.docker.elastic.co/
matrix:
  include:
  - env: ELASTIC_STACK_VERSION=5.6.9
  - env: ELASTIC_STACK_VERSION=6.1.4
  - env: ELASTIC_STACK_VERSION=6.2.4
  fast_finish: true
install: true
script: ci/unit/run.sh
